# Generated by Django 4.1.5 on 2023-01-12 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import donutapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=100)),
                ('count_posts', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('img', models.ImageField(default='images/default.png', upload_to='images/')),
                ('male', models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default='male', max_length=6)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_code/')),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=donutapp.models.default_datetime)),
                ('img', models.ImageField(upload_to='posts/')),
                ('liked', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='donutapp.profile')),
            ],
        ),
    ]
