# Generated by Django 4.1.5 on 2023-01-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donutapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
    ]
