# Generated by Django 4.1.5 on 2023-01-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donutapp', '0002_remove_profile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='count_posts',
        ),
    ]
