# Generated by Django 4.1.5 on 2023-01-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donutapp', '0003_remove_profile_count_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
